#ifndef HELPDESK_H
#define HELPDESK_H

#include "Section.h"
#include "Person.h" 
#include "Staff.h"

/**
 * @file HelpDesk.h
 * @brief Concrete Section used for help/assistance chat and requests.
 * @author Sente
 * @date October 26, 2025
 */

/**
 * @class HelpDesk
 * @brief A HelpDesk is a concrete Section that broadcasts messages to all
 *        participants and routes help requests to the admin or the first
 *        available Staff handler in the section. Behaviour mirrors Section
 *        derived types such as SalesRoom but is intended for assistance.
 */

class HelpDesk :public Section {

public:
	/**
     * @brief Constructs a HelpDesk with the given name.
     * @param name The human-readable name of the section.
     */
	HelpDesk(std::string name);

	/**
     * @brief Notify all relevant persons of an event generated by person.
     * @details Broadcasts the sender's message to all participants, then
     *          invokes the admin's request handler (if set). If no admin is
     *          set, the first Staff found in the section will be asked to
     *          handle the request.
     * @param person The person that triggered the notification.
     */
	void notify(Person* person);
};

#endif
