
#ifndef SALESROOM_H
#define SALESROOM_H

#include "Section.h"
#include "Person.h" 
#include "Staff.h"
/**
 * @file SalesRoom.h
 * @brief Concrete Section used for sales-related chat and requests.
 * @author Sente
 * @date October 26, 2025
 */
/**
 * @class SalesRoom
 * @brief A SalesRoom is a concrete Section that broadcasts messages to all
 *        participants and routes requests to the admin or the first available
 *        Staff handler in the section.
 */

class SalesRoom :public Section {

	public:
		/**
		 * @brief Constructs a SalesRoom with the given name.
		 * @param name The human-readable name of the section.
		 */
		SalesRoom(std::string name);

		/**
         * @brief Notify all relevant persons of an event generated by person.
         * @details Broadcasts the sender's message to all participants, then
         *          invokes the admin's request handler (if set). If no admin is
         *          set, the first Staff found in the section will be asked to
         *          handle the request.
         * @param person The person that triggered the notification.
         */
		void notify(Person* person);


		virtual ~SalesRoom() = default ;
};

#endif
