
#ifndef SECTION_H
#define SECTION_H


#include "Iterator.h"
#include "ChatIterator.h"


#include <string>
#include <vector>

/**
 * @file Section.h
 * @brief Abstract class representing a chat section/group within the system.
 * @author Sente
 * @date October 26, 2025
 *
 * @class Section
 * @brief A Section manages a collection of Person instances, maintains a history of
 * messages, and provides an interface to notify participants when a Person
 * sends a message or makes a request. Concrete Section types implement the
 * notify(Person*) method to define how messages are propagated Sections also provide an
 * iterator for traversing the contained chat history.
 */
class Person;
class Staff;
class Section {

	public:

		/**
         * @brief Constructs a Section with the given name.
         * @param name The human-readable name of the section.
         */
		Section(std::string name);

		/**
         * @brief Destroys the Section and releases any runtime resources.
         */
		~Section();

		friend class Iterator;

		/**
         * @brief Notify all relevant persons of an event generated by person.
         * @details Must be implemented by concrete Section subclasses to define
         *          how a Person's sendMessage is routed to other participants.
         * @param person The person that triggered the notification.
         */
		virtual void notify(Person* person) = 0;

		/**
         * @brief Adds a Person to this Section.
         * @param person Pointer to the Person to add.
         */
		void addPerson(Person* person);

		/**
         * @brief Sets the administrative Staff member for this Section.
         * @param admin Pointer to the Staff who is the admin for this section.
         */
		void setAdmin(Staff* admin);
		
		/**
         * @brief Removes a Person from this Section.
         * @param person Pointer to the Person to remove.
         * @return The removed Person pointer on success, or nullptr if not found.
         */
		Person* removePerson(Person* person);

		 /**
         * @brief Creates an iterator for traversing persons in this Section.
         * @return A newly allocated Iterator (caller is responsible for deletion).
         */
		Iterator* createIterator();

		/**
         * @brief Returns the name of the Section.
         * @return The section name.
         */
		std::string getName() const;

		/**
         * @brief Returns a formatted history of messages for this Section.
         * @return A string containing the section's message history.
         */
		std::string getHistory() const;

		/**
         * @brief Appends the provided Person's most recent message to the history.
         * @param person The Person whose message should be recorded.
         */
		void addToHistory(Person* person);

	private:
		std::string name;
		std::vector<std::string> history;

	protected:
		Staff* admin;
		std::vector<Person*> personList;
};

#endif
